security:
  jwt:
    key-store: classpath:keystore.jks
    key-store-password: changeit
    key-pair-alias: oauth2server
    key-pair-password: changeit

spring:
  jackson:
    serialization:
      INDENT_OUTPUT: true