server:
  port: 9090
---
spring:
  cloud:
    gateway:
      default-filters:
      - name: SCGWGlobalFilter
      routes:
        - id: nt-ms1
          uri: http://train.tekmlai.com/
          predicates:
            - Path=/mcservice1/**
          filters:
          - name: SCGWPreFilter
          - name: SCGWPostFilter
        - id: nt-ms2
          uri: http://basicauth.tekmlai.com/
          predicates:
            - Path=/mcservice2/**